apiVersion: apps/v1
kind: Deployment
metadata:
  name: codex-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codex-springboot
  template:
    metadata:
      labels:
        app: codex-springboot
    spec:
      containers:
        - name: springboot
          image: ositagbo/codex-docker-demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: codex-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: codex-springboot
